from _typeshed import Incomplete

def fourier_gaussian(input, sigma, n: int = ..., axis: int = ..., output: Incomplete | None = ...): ...
def fourier_uniform(input, size, n: int = ..., axis: int = ..., output: Incomplete | None = ...): ...
def fourier_ellipsoid(input, size, n: int = ..., axis: int = ..., output: Incomplete | None = ...): ...
def fourier_shift(input, shift, n: int = ..., axis: int = ..., output: Incomplete | None = ...): ...
