from _typeshed import Incomplete

def label(input, structure: Incomplete | None = ..., output: Incomplete | None = ...): ...
def find_objects(input, max_label: int = ...): ...
def value_indices(arr, *, ignore_value: Incomplete | None = ...): ...
def labeled_comprehension(input, labels, index, func, out_dtype, default, pass_positions: bool = ...): ...
def sum(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def sum_labels(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def mean(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def variance(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def standard_deviation(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def minimum(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def maximum(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def median(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def minimum_position(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def maximum_position(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def extrema(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def center_of_mass(input, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def histogram(input, min, max, bins, labels: Incomplete | None = ..., index: Incomplete | None = ...): ...
def watershed_ift(input, markers, structure: Incomplete | None = ..., output: Incomplete | None = ...): ...
