# Names in __all__ with no definition:
#   convolve
#   convolve1d
#   correlate
#   correlate1d
#   gaussian_filter
#   gaussian_filter1d
#   gaussian_gradient_magnitude
#   gaussian_laplace
#   generic_filter
#   generic_filter1d
#   generic_gradient_magnitude
#   generic_laplace
#   laplace
#   maximum_filter
#   maximum_filter1d
#   median_filter
#   minimum_filter
#   minimum_filter1d
#   normalize_axis_index
#   percentile_filter
#   prewitt
#   rank_filter
#   sobel
#   uniform_filter
#   uniform_filter1d
