__f2py_numpy_version__: str
__version__: str
cnaupd: fortran
cneupd: fortran
debug: fortran
dnaupd: fortran
dneupd: fortran
dsaupd: fortran
dseupd: fortran
snaupd: fortran
sneupd: fortran
ssaupd: fortran
sseupd: fortran
timing: fortran
znaupd: fortran
zneupd: fortran
