import numpy

def cdist_braycurtis(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_canberra(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_chebyshev(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_cityblock(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_dice(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_euclidean(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_hamming(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_jaccard(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_kulczynski1(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_minkowski(x: object, y: object, w: object = ..., out: object = ..., p: float = ...) -> numpy.ndarray: ...
def cdist_rogerstanimoto(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_russellrao(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_sokalmichener(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_sokalsneath(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_sqeuclidean(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def cdist_yule(x: object, y: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_braycurtis(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_canberra(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_chebyshev(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_cityblock(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_dice(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_euclidean(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_hamming(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_jaccard(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_kulczynski1(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_minkowski(x: object, w: object = ..., out: object = ..., p: float = ...) -> numpy.ndarray: ...
def pdist_rogerstanimoto(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_russellrao(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_sokalmichener(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_sokalsneath(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_sqeuclidean(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
def pdist_yule(x: object, w: object = ..., out: object = ...) -> numpy.ndarray: ...
