from _typeshed import Incomplete

def delaunay_plot_2d(tri, ax: Incomplete | None = ...): ...
def convex_hull_plot_2d(hull, ax: Incomplete | None = ...): ...
def voronoi_plot_2d(vor, ax: Incomplete | None = ..., **kw): ...
