from _typeshed import Incomplete

class LineSearchWarning(RuntimeWarning): ...

def line_search_wolfe1(f, fprime, xk, pk, gfk: Incomplete | None = ..., old_fval: Incomplete | None = ..., old_old_fval: Incomplete | None = ..., args=..., c1: float = ..., c2: float = ..., amax: int = ..., amin: float = ..., xtol: float = ...): ...
def scalar_search_wolfe1(phi, derphi, phi0: Incomplete | None = ..., old_phi0: Incomplete | None = ..., derphi0: Incomplete | None = ..., c1: float = ..., c2: float = ..., amax: int = ..., amin: float = ..., xtol: float = ...): ...
line_search = line_search_wolfe1

def line_search_wolfe2(f, myfprime, xk, pk, gfk: Incomplete | None = ..., old_fval: Incomplete | None = ..., old_old_fval: Incomplete | None = ..., args=..., c1: float = ..., c2: float = ..., amax: Incomplete | None = ..., extra_condition: Incomplete | None = ..., maxiter: int = ...): ...
def scalar_search_wolfe2(phi, derphi, phi0: Incomplete | None = ..., old_phi0: Incomplete | None = ..., derphi0: Incomplete | None = ..., c1: float = ..., c2: float = ..., amax: Incomplete | None = ..., extra_condition: Incomplete | None = ..., maxiter: int = ...): ...
def line_search_armijo(f, xk, pk, gfk, old_fval, args=..., c1: float = ..., alpha0: int = ...): ...
