from _typeshed import Incomplete

def linprog_verbose_callback(res): ...
def linprog_terse_callback(res) -> None: ...
def linprog(c, A_ub: Incomplete | None = ..., b_ub: Incomplete | None = ..., A_eq: Incomplete | None = ..., b_eq: Incomplete | None = ..., bounds: Incomplete | None = ..., method: str = ..., callback: Incomplete | None = ..., options: Incomplete | None = ..., x0: Incomplete | None = ..., integrality: Incomplete | None = ...): ...
