from _typeshed import Incomplete

def fsolve(func, x0, args=..., fprime: Incomplete | None = ..., full_output: int = ..., col_deriv: int = ..., xtol: float = ..., maxfev: int = ..., band: Incomplete | None = ..., epsfcn: Incomplete | None = ..., factor: int = ..., diag: Incomplete | None = ...): ...
def leastsq(func, x0, args=..., Dfun: Incomplete | None = ..., full_output: bool = ..., col_deriv: bool = ..., ftol: float = ..., xtol: float = ..., gtol: float = ..., maxfev: int = ..., epsfcn: Incomplete | None = ..., factor: int = ..., diag: Incomplete | None = ...): ...
def curve_fit(f, xdata, ydata, p0: Incomplete | None = ..., sigma: Incomplete | None = ..., absolute_sigma: bool = ..., check_finite: Incomplete | None = ..., bounds=..., method: Incomplete | None = ..., jac: Incomplete | None = ..., *, full_output: bool = ..., nan_policy: Incomplete | None = ..., **kwargs): ...
def fixed_point(func, x0, args=..., xtol: float = ..., maxiter: int = ..., method: str = ...): ...
