from _typeshed import Incomplete

def minimize(fun, x0, args=..., method: Incomplete | None = ..., jac: Incomplete | None = ..., hess: Incomplete | None = ..., hessp: Incomplete | None = ..., bounds: Incomplete | None = ..., constraints=..., tol: Incomplete | None = ..., callback: Incomplete | None = ..., options: Incomplete | None = ...): ...
def minimize_scalar(fun, bracket: Incomplete | None = ..., bounds: Incomplete | None = ..., args=..., method: Incomplete | None = ..., tol: Incomplete | None = ..., options: Incomplete | None = ...): ...
