from _typeshed import Incomplete

def approx_jacobian(x, func, epsilon, *args): ...
def fmin_slsqp(func, x0, eqcons=..., f_eqcons: Incomplete | None = ..., ieqcons=..., f_ieqcons: Incomplete | None = ..., bounds=..., fprime: Incomplete | None = ..., fprime_eqcons: Incomplete | None = ..., fprime_ieqcons: Incomplete | None = ..., args=..., iter: int = ..., acc: float = ..., iprint: int = ..., disp: Incomplete | None = ..., full_output: int = ..., epsilon=..., callback: Incomplete | None = ...): ...
