from ._trustregion import BaseQuadraticSubproblem as BaseQuadraticSubproblem

class DoglegSubproblem(BaseQuadraticSubproblem):
    def cauchy_point(self): ...
    def newton_point(self): ...
    def solve(self, trust_radius): ...
