from _typeshed import Incomplete

description: str

def f1(x): ...
def f1_fp(x): ...
def f1_fpp(x): ...
def f2(x): ...
def f2_fp(x): ...
def f2_fpp(x): ...
def f3(x): ...
def f3_fp(x): ...
def f3_fpp(x): ...
def f4(x): ...
def f5(x): ...
def f6(x): ...
def aps01_f(x): ...
def aps01_fp(x): ...
def aps01_fpp(x): ...
def aps02_f(x): ...
def aps02_fp(x): ...
def aps02_fpp(x): ...
def aps03_f(x, a, b): ...
def aps03_fp(x, a, b): ...
def aps03_fpp(x, a, b): ...
def aps04_f(x, n, a): ...
def aps04_fp(x, n, a): ...
def aps04_fpp(x, n, a): ...
def aps05_f(x): ...
def aps05_fp(x): ...
def aps05_fpp(x): ...
def aps06_f(x, n): ...
def aps06_fp(x, n): ...
def aps06_fpp(x, n): ...
def aps07_f(x, n): ...
def aps07_fp(x, n): ...
def aps07_fpp(x, n): ...
def aps08_f(x, n): ...
def aps08_fp(x, n): ...
def aps08_fpp(x, n): ...
def aps09_f(x, n): ...
def aps09_fp(x, n): ...
def aps09_fpp(x, n): ...
def aps10_f(x, n): ...
def aps10_fp(x, n): ...
def aps10_fpp(x, n): ...
def aps11_f(x, n): ...
def aps11_fp(x, n): ...
def aps11_fpp(x, n): ...
def aps12_f(x, n): ...
def aps12_fp(x, n): ...
def aps12_fpp(x, n): ...
def aps13_f(x): ...
def aps13_fp(x): ...
def aps13_fpp(x): ...
def aps14_f(x, n): ...
def aps14_fp(x, n): ...
def aps14_fpp(x, n): ...
def aps15_f(x, n): ...
def aps15_fp(x, n): ...
def aps15_fpp(x, n): ...
def cplx01_f(z, n, a): ...
def cplx01_fp(z, n, a): ...
def cplx01_fpp(z, n, a): ...
def cplx02_f(z, a): ...
def cplx02_fp(z, a): ...
def cplx02_fpp(z, a): ...
def get_tests(collection: str = ..., smoothness: Incomplete | None = ...): ...

methods: Incomplete
mstrings: Incomplete
functions: Incomplete
fstrings: Incomplete

def fun1(x): ...
def fun2(x): ...
def fun3(x): ...
def fun4(x): ...
def fun5(x): ...
def fun6(x): ...
def fun7(x): ...
def fun8(x): ...
def fun9(x): ...
