import scipy.stats as stats
from _typeshed import Incomplete
from scipy._lib._util import check_random_state as check_random_state
from scipy.stats._distn_infrastructure import argsreduce as argsreduce, rv_frozen as rv_frozen
from typing import Any, ClassVar, overload

__test__: dict

class DiscreteAliasUrn(Method):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class DiscreteGuideTable(Method):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def ppf(self, u) -> Any: ...

class Method:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def rvs(self, size=..., random_state=...) -> Any: ...
    def set_random_state(self, random_state=...) -> Any: ...
    def __reduce__(self): ...

class NumericalInverseHermite(Method):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    intervals: Incomplete
    midpoint_error: Incomplete
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def ppf(self, u) -> Any: ...
    def qrvs(self, size=..., d=..., qmc_engine=...) -> Any: ...
    def u_error(self, sample_size=...) -> Any: ...

class NumericalInversePolynomial(Method):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    intervals: Incomplete
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def cdf(self, x) -> Any: ...
    def ppf(self, u) -> Any: ...
    def qrvs(self, size=..., d=..., qmc_engine=...) -> Any: ...
    def u_error(self, sample_size=...) -> Any: ...

class SimpleRatioUniforms(Method):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class TransformedDensityRejection(Method):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    hat_area: Incomplete
    squeeze_area: Incomplete
    squeeze_hat_ratio: Incomplete
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @overload
    def ppf_hat(self, u) -> Any: ...
    @overload
    def ppf_hat(self, u) -> Any: ...

class UNURANError(RuntimeError): ...

class _URNG:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...
