from scipy.sparse._base import issparse as issparse
from scipy.sparse._csr import csr_matrix as csr_matrix
from typing import Any, overload

__test__: dict

@overload
def construct_dist_matrix(graph, predecessors, directed=..., null_value=...) -> Any: ...
@overload
def construct_dist_matrix(graph=..., predecessors=..., directed=...) -> Any: ...
@overload
def csgraph_from_dense(graph, null_value=..., nan_null=..., infinity_null=...) -> Any: ...
@overload
def csgraph_from_dense(graph) -> Any: ...
@overload
def csgraph_from_masked(graph) -> Any: ...
@overload
def csgraph_from_masked(graph_masked) -> Any: ...
@overload
def csgraph_masked_from_dense(graph, null_value=..., nan_null=..., 
infinity_null=..., copy=...) -> Any: ...
@overload
def csgraph_masked_from_dense(graph) -> Any: ...
def csgraph_to_dense(csgraph, null_value=...) -> Any: ...
@overload
def csgraph_to_masked(csgraph) -> Any: ...
@overload
def csgraph_to_masked(graph) -> Any: ...
@overload
def reconstruct_path(csgraph, predecessors, directed=...) -> Any: ...
@overload
def reconstruct_path(csgraph=..., predecessors=..., directed=...) -> Any: ...
