from _typeshed import Incomplete

def axis_slice(a, start: Incomplete | None = ..., stop: Incomplete | None = ..., step: Incomplete | None = ..., axis: int = ...): ...
def axis_reverse(a, axis: int = ...): ...
def odd_ext(x, n, axis: int = ...): ...
def even_ext(x, n, axis: int = ...): ...
def const_ext(x, n, axis: int = ...): ...
def zero_ext(x, n, axis: int = ...): ...
