def spline_filter(Iin, lmbda: float = ...): ...
def bspline(x, n): ...
def gauss_spline(x, n): ...
def cubic(x): ...
def quadratic(x): ...
def cspline1d(signal, lamb: float = ...): ...
def qspline1d(signal, lamb: float = ...): ...
def cspline1d_eval(cj, newx, dx: float = ..., x0: int = ...): ...
def qspline1d_eval(cj, newx, dx: float = ..., x0: int = ...): ...
