from _typeshed import Incomplete

def kaiser_beta(a): ...
def kaiser_atten(numtaps, width): ...
def kaiserord(ripple, width): ...
def firwin(numtaps, cutoff, width: Incomplete | None = ..., window: str = ..., pass_zero: bool = ..., scale: bool = ..., nyq: Incomplete | None = ..., fs: Incomplete | None = ...): ...
def firwin2(numtaps, freq, gain, nfreqs: Incomplete | None = ..., window: str = ..., nyq: Incomplete | None = ..., antisymmetric: bool = ..., fs: Incomplete | None = ...): ...
def remez(numtaps, bands, desired, weight: Incomplete | None = ..., Hz: Incomplete | None = ..., type: str = ..., maxiter: int = ..., grid_density: int = ..., fs: Incomplete | None = ...): ...
def firls(numtaps, bands, desired, weight: Incomplete | None = ..., nyq: Incomplete | None = ..., fs: Incomplete | None = ...): ...
def minimum_phase(h, method: str = ..., n_fft: Incomplete | None = ...): ...
