from _typeshed import Incomplete

def tf2ss(num, den): ...
def abcd_normalize(A: Incomplete | None = ..., B: Incomplete | None = ..., C: Incomplete | None = ..., D: Incomplete | None = ...): ...
def ss2tf(A, B, C, D, input: int = ...): ...
def zpk2ss(z, p, k): ...
def ss2zpk(A, B, C, D, input: int = ...): ...
def cont2discrete(system, dt, method: str = ..., alpha: Incomplete | None = ...): ...
