from _typeshed import Incomplete

def argrelmin(data, axis: int = ..., order: int = ..., mode: str = ...): ...
def argrelmax(data, axis: int = ..., order: int = ..., mode: str = ...): ...
def argrelextrema(data, comparator, axis: int = ..., order: int = ..., mode: str = ...): ...
def peak_prominences(x, peaks, wlen: Incomplete | None = ...): ...
def peak_widths(x, peaks, rel_height: float = ..., prominence_data: Incomplete | None = ..., wlen: Incomplete | None = ...): ...
def find_peaks(x, height: Incomplete | None = ..., threshold: Incomplete | None = ..., distance: Incomplete | None = ..., prominence: Incomplete | None = ..., width: Incomplete | None = ..., wlen: Incomplete | None = ..., rel_height: float = ..., plateau_size: Incomplete | None = ...): ...
def find_peaks_cwt(vector, widths, wavelet: Incomplete | None = ..., max_distances: Incomplete | None = ..., gap_thresh: Incomplete | None = ..., min_length: Incomplete | None = ..., min_snr: int = ..., noise_perc: int = ..., window_size: Incomplete | None = ...): ...
