from _typeshed import Incomplete

def correlate(in1, in2, mode: str = ..., method: str = ...): ...
def correlation_lags(in1_len, in2_len, mode: str = ...): ...
def fftconvolve(in1, in2, mode: str = ..., axes: Incomplete | None = ...): ...
def oaconvolve(in1, in2, mode: str = ..., axes: Incomplete | None = ...): ...
def choose_conv_method(in1, in2, mode: str = ..., measure: bool = ...): ...
def convolve(in1, in2, mode: str = ..., method: str = ...): ...
def order_filter(a, domain, rank): ...
def medfilt(volume, kernel_size: Incomplete | None = ...): ...
def wiener(im, mysize: Incomplete | None = ..., noise: Incomplete | None = ...): ...
def convolve2d(in1, in2, mode: str = ..., boundary: str = ..., fillvalue: int = ...): ...
def correlate2d(in1, in2, mode: str = ..., boundary: str = ..., fillvalue: int = ...): ...
def medfilt2d(input, kernel_size: int = ...): ...
def lfilter(b, a, x, axis: int = ..., zi: Incomplete | None = ...): ...
def lfiltic(b, a, y, x: Incomplete | None = ...): ...
def deconvolve(signal, divisor): ...
def hilbert(x, N: Incomplete | None = ..., axis: int = ...): ...
def hilbert2(x, N: Incomplete | None = ...): ...
def cmplx_sort(p): ...
def unique_roots(p, tol: float = ..., rtype: str = ...): ...
def invres(r, p, k, tol: float = ..., rtype: str = ...): ...
def residue(b, a, tol: float = ..., rtype: str = ...): ...
def residuez(b, a, tol: float = ..., rtype: str = ...): ...
def invresz(r, p, k, tol: float = ..., rtype: str = ...): ...
def resample(x, num, t: Incomplete | None = ..., axis: int = ..., window: Incomplete | None = ..., domain: str = ...): ...
def resample_poly(x, up, down, axis: int = ..., window=..., padtype: str = ..., cval: Incomplete | None = ...): ...
def vectorstrength(events, period): ...
def detrend(data, axis: int = ..., type: str = ..., bp: int = ..., overwrite_data: bool = ...): ...
def lfilter_zi(b, a): ...
def sosfilt_zi(sos): ...
def filtfilt(b, a, x, axis: int = ..., padtype: str = ..., padlen: Incomplete | None = ..., method: str = ..., irlen: Incomplete | None = ...): ...
def sosfilt(sos, x, axis: int = ..., zi: Incomplete | None = ...): ...
def sosfiltfilt(sos, x, axis: int = ..., padtype: str = ..., padlen: Incomplete | None = ...): ...
def decimate(x, q, n: Incomplete | None = ..., ftype: str = ..., axis: int = ..., zero_phase: bool = ...): ...
