from _typeshed import Incomplete

def lombscargle(x, y, freqs, precenter: bool = ..., normalize: bool = ...): ...
def periodogram(x, fs: float = ..., window: str = ..., nfft: Incomplete | None = ..., detrend: str = ..., return_onesided: bool = ..., scaling: str = ..., axis: int = ...): ...
def welch(x, fs: float = ..., window: str = ..., nperseg: Incomplete | None = ..., noverlap: Incomplete | None = ..., nfft: Incomplete | None = ..., detrend: str = ..., return_onesided: bool = ..., scaling: str = ..., axis: int = ..., average: str = ...): ...
def csd(x, y, fs: float = ..., window: str = ..., nperseg: Incomplete | None = ..., noverlap: Incomplete | None = ..., nfft: Incomplete | None = ..., detrend: str = ..., return_onesided: bool = ..., scaling: str = ..., axis: int = ..., average: str = ...): ...
def spectrogram(x, fs: float = ..., window=..., nperseg: Incomplete | None = ..., noverlap: Incomplete | None = ..., nfft: Incomplete | None = ..., detrend: str = ..., return_onesided: bool = ..., scaling: str = ..., axis: int = ..., mode: str = ...): ...
def check_COLA(window, nperseg, noverlap, tol: float = ...): ...
def check_NOLA(window, nperseg, noverlap, tol: float = ...): ...
def stft(x, fs: float = ..., window: str = ..., nperseg: int = ..., noverlap: Incomplete | None = ..., nfft: Incomplete | None = ..., detrend: bool = ..., return_onesided: bool = ..., boundary: str = ..., padded: bool = ..., axis: int = ..., scaling: str = ...): ...
def istft(Zxx, fs: float = ..., window: str = ..., nperseg: Incomplete | None = ..., noverlap: Incomplete | None = ..., nfft: Incomplete | None = ..., input_onesided: bool = ..., boundary: bool = ..., time_axis: int = ..., freq_axis: int = ..., scaling: str = ...): ...
def coherence(x, y, fs: float = ..., window: str = ..., nperseg: Incomplete | None = ..., noverlap: Incomplete | None = ..., nfft: Incomplete | None = ..., detrend: str = ..., axis: int = ...): ...
