from typing import Any

def cspline2d(input, _lambda=..., precision=...) -> Any: ...
def qspline2d(input, _lambda=..., precision=...) -> Any: ...
def sepfir2d(input, hrow, hcol) -> Any: ...
def symiirorder1(*args, **kwargs): ...
def symiirorder2(*args, **kwargs): ...
