from ._upfirdn_apply import _output_len as _output_len

class _UpFIRDn:
    def __init__(self, h, x_dtype, up, down) -> None: ...
    def apply_filter(self, x, axis: int = ..., mode: str = ..., cval: int = ...): ...

def upfirdn(h, x, up: int = ..., down: int = ..., axis: int = ..., mode: str = ..., cval: int = ...): ...
