from _typeshed import Incomplete

def sawtooth(t, width: int = ...): ...
def square(t, duty: float = ...): ...
def gausspulse(t, fc: int = ..., bw: float = ..., bwr: int = ..., tpr: int = ..., retquad: bool = ..., retenv: bool = ...): ...
def chirp(t, f0, t1, f1, method: str = ..., phi: int = ..., vertex_zero: bool = ...): ...
def sweep_poly(t, poly, phi: int = ...): ...
def unit_impulse(shape, idx: Incomplete | None = ..., dtype=...): ...
