from _typeshed import Incomplete

def daub(p): ...
def qmf(hk): ...
def cascade(hk, J: int = ...): ...
def morlet(M, w: float = ..., s: float = ..., complete: bool = ...): ...
def ricker(points, a): ...
def morlet2(M, s, w: int = ...): ...
def cwt(data, wavelet, widths, dtype: Incomplete | None = ..., **kwargs): ...
