def icosahedral(cls): ...
def octahedral(cls): ...
def tetrahedral(cls): ...
def dicyclic(cls, n, axis: int = ...): ...
def cyclic(cls, n, axis: int = ...): ...
def create_group(cls, group, axis: str = ...): ...
