from _typeshed import Incomplete

def logsumexp(a, axis: Incomplete | None = ..., b: Incomplete | None = ..., keepdims: bool = ..., return_sign: bool = ...): ...
def softmax(x, axis: Incomplete | None = ...): ...
def log_softmax(x, axis: Incomplete | None = ...): ...
