__f2py_numpy_version__: str
__version__: str
airyzo: fortran
bernob: fortran
cerzo: fortran
clpmn: fortran
clpn: fortran
clqmn: fortran
clqn: fortran
cpbdn: fortran
cyzo: fortran
eulerb: fortran
fcoef: fortran
fcszo: fortran
jdzo: fortran
jyzo: fortran
klvnzo: fortran
lamn: fortran
lamv: fortran
lpmn: fortran
lpn: fortran
lqmn: fortran
lqnb: fortran
pbdv: fortran
rctj: fortran
rcty: fortran
segv: fortran
