def spherical_jn(n, z, derivative: bool = ...): ...
def spherical_yn(n, z, derivative: bool = ...): ...
def spherical_in(n, z, derivative: bool = ...): ...
def spherical_kn(n, z, derivative: bool = ...): ...
