# Names in __all__ with no definition:
#   airy
#   arange
#   around
#   c_roots
#   cg_roots
#   chebyc
#   chebys
#   chebyt
#   chebyu
#   exp
#   floor
#   gegenbauer
#   genlaguerre
#   h_roots
#   he_roots
#   hermite
#   hermitenorm
#   hstack
#   inf
#   j_roots
#   jacobi
#   js_roots
#   l_roots
#   la_roots
#   laguerre
#   legendre
#   linalg
#   newfun
#   oldfun
#   orthopoly1d
#   p_roots
#   ps_roots
#   roots_chebyc
#   roots_chebys
#   roots_chebyt
#   roots_chebyu
#   roots_gegenbauer
#   roots_genlaguerre
#   roots_hermite
#   roots_hermitenorm
#   roots_jacobi
#   roots_laguerre
#   roots_legendre
#   roots_sh_chebyt
#   roots_sh_chebyu
#   roots_sh_jacobi
#   roots_sh_legendre
#   s_roots
#   sh_chebyt
#   sh_chebyu
#   sh_jacobi
#   sh_legendre
#   t_roots
#   ts_roots
#   u_roots
#   us_roots
