from _typeshed import Incomplete

class ODEintWarning(Warning): ...

def odeint(func, y0, t, args=..., Dfun: Incomplete | None = ..., col_deriv: int = ..., full_output: int = ..., ml: Incomplete | None = ..., mu: Incomplete | None = ..., rtol: Incomplete | None = ..., atol: Incomplete | None = ..., tcrit: Incomplete | None = ..., h0: float = ..., hmax: float = ..., hmin: float = ..., ixpr: int = ..., mxstep: int = ..., mxhnil: int = ..., mxordn: int = ..., mxords: int = ..., printmessg: int = ..., tfirst: bool = ...): ...
