from typing import Any, overload

__pyx_capi__: dict
__test__: dict
bandwidth_c: fused_cython_function
bandwidth_noncontig: fused_cython_function
find_det_from_lu: fused_cython_function
is_sym_her_complex_c: fused_cython_function
is_sym_her_complex_noncontig: fused_cython_function
is_sym_her_real_c: fused_cython_function
is_sym_her_real_noncontig: fused_cython_function

@overload
def bandwidth(a) -> Any: ...
@overload
def bandwidth(A) -> Any: ...
@overload
def ishermitian(a, atol=..., rtol=...) -> Any: ...
@overload
def ishermitian(A) -> Any: ...
@overload
def ishermitian(A) -> Any: ...
@overload
def ishermitian(Ac) -> Any: ...
@overload
def ishermitian(Af) -> Any: ...
@overload
def ishermitian(Af, atol=...) -> Any: ...
@overload
def issymmetric(a, atol=..., rtol=...) -> Any: ...
@overload
def issymmetric(A) -> Any: ...
@overload
def issymmetric(Ac) -> Any: ...
