def lu_factor(a, overwrite_a: bool = ..., check_finite: bool = ...): ...
def lu_solve(lu_and_piv, b, trans: int = ..., overwrite_b: bool = ..., check_finite: bool = ...): ...
def lu(a, permute_l: bool = ..., overwrite_a: bool = ..., check_finite: bool = ..., p_indices: bool = ...): ...
