from _typeshed import Incomplete

def qz(A, B, output: str = ..., lwork: Incomplete | None = ..., sort: Incomplete | None = ..., overwrite_a: bool = ..., overwrite_b: bool = ..., check_finite: bool = ...): ...
def ordqz(A, B, sort: str = ..., output: str = ..., overwrite_a: bool = ..., overwrite_b: bool = ..., check_finite: bool = ...): ...
