def cholesky(a, lower: bool = ..., overwrite_a: bool = ..., check_finite: bool = ...): ...
def cho_factor(a, lower: bool = ..., overwrite_a: bool = ..., check_finite: bool = ...): ...
def cho_solve(c_and_lower, b, overwrite_b: bool = ..., check_finite: bool = ...): ...
def cholesky_banded(ab, overwrite_ab: bool = ..., lower: bool = ..., check_finite: bool = ...): ...
def cho_solve_banded(cb_and_lower, b, overwrite_b: bool = ..., check_finite: bool = ...): ...
