from _typeshed import Incomplete

def schur(a, output: str = ..., lwork: Incomplete | None = ..., overwrite_a: bool = ..., sort: Incomplete | None = ..., check_finite: bool = ...): ...
def rsf2csf(T, Z, check_finite: bool = ...): ...
