from _typeshed import Incomplete

def svd(a, full_matrices: bool = ..., compute_uv: bool = ..., overwrite_a: bool = ..., check_finite: bool = ..., lapack_driver: str = ...): ...
def svdvals(a, overwrite_a: bool = ..., check_finite: bool = ...): ...
def diagsvd(s, M, N): ...
def orth(A, rcond: Incomplete | None = ...): ...
def null_space(A, rcond: Incomplete | None = ...): ...
def subspace_angles(A, B): ...
