from _typeshed import Incomplete

def eig(a, b: Incomplete | None = ..., left: bool = ..., right: bool = ..., overwrite_a: bool = ..., overwrite_b: bool = ..., check_finite: bool = ..., homogeneous_eigvals: bool = ...): ...
def eigh(a, b: Incomplete | None = ..., lower: bool = ..., eigvals_only: bool = ..., overwrite_a: bool = ..., overwrite_b: bool = ..., turbo: bool = ..., eigvals: Incomplete | None = ..., type: int = ..., check_finite: bool = ..., subset_by_index: Incomplete | None = ..., subset_by_value: Incomplete | None = ..., driver: Incomplete | None = ...): ...
def eig_banded(a_band, lower: bool = ..., eigvals_only: bool = ..., overwrite_a_band: bool = ..., select: str = ..., select_range: Incomplete | None = ..., max_ev: int = ..., check_finite: bool = ...): ...
def eigvals(a, b: Incomplete | None = ..., overwrite_a: bool = ..., check_finite: bool = ..., homogeneous_eigvals: bool = ...): ...
def eigvalsh(a, b: Incomplete | None = ..., lower: bool = ..., overwrite_a: bool = ..., overwrite_b: bool = ..., turbo: bool = ..., eigvals: Incomplete | None = ..., type: int = ..., check_finite: bool = ..., subset_by_index: Incomplete | None = ..., subset_by_value: Incomplete | None = ..., driver: Incomplete | None = ...): ...
def eigvals_banded(a_band, lower: bool = ..., overwrite_a_band: bool = ..., select: str = ..., select_range: Incomplete | None = ..., check_finite: bool = ...): ...
def eigvalsh_tridiagonal(d, e, select: str = ..., select_range: Incomplete | None = ..., check_finite: bool = ..., tol: float = ..., lapack_driver: str = ...): ...
def eigh_tridiagonal(d, e, eigvals_only: bool = ..., select: str = ..., select_range: Incomplete | None = ..., check_finite: bool = ..., tol: float = ..., lapack_driver: str = ...): ...
def hessenberg(a, calc_q: bool = ..., overwrite_a: bool = ..., check_finite: bool = ...): ...
def cdf2rdf(w, v): ...
