from typing import Any, overload

__test__: dict

def qr_delete(Q, R, k, intp=..., which=..., overwrite_qr=..., check_finite=...) -> Any: ...
def qr_insert(Q, R, u, k, which=..., rcond=..., overwrite_qru=..., check_finite=...) -> Any: ...
@overload
def qr_update(Q, R, u, v, overwrite_qruv=..., check_finite=...) -> Any: ...
@overload
def qr_update(q, r, u, v, _False) -> Any: ...
@overload
def qr_update(qe, re, u, v, _False) -> Any: ...
@overload
def qr_update(q, r, u2, v2, _False) -> Any: ...
