from _typeshed import Incomplete

def qr(a, overwrite_a: bool = ..., lwork: Incomplete | None = ..., mode: str = ..., pivoting: bool = ..., check_finite: bool = ...): ...
def qr_multiply(a, c, mode: str = ..., pivoting: bool = ..., conjugate: bool = ..., overwrite_a: bool = ..., overwrite_c: bool = ...): ...
def rq(a, overwrite_a: bool = ..., lwork: Incomplete | None = ..., mode: str = ..., check_finite: bool = ...): ...
