__f2py_numpy_version__: str
__version__: str
caxpy: fortran
ccopy: fortran
cdotc: fortran
cdotu: fortran
cgbmv: fortran
cgemm: fortran
cgemv: fortran
cgerc: fortran
cgeru: fortran
chbmv: fortran
chemm: fortran
chemv: fortran
cher: fortran
cher2: fortran
cher2k: fortran
cherk: fortran
chpmv: fortran
chpr: fortran
chpr2: fortran
crotg: fortran
cscal: fortran
cspmv: fortran
cspr: fortran
csrot: fortran
csscal: fortran
cswap: fortran
csymm: fortran
csyr: fortran
csyr2k: fortran
csyrk: fortran
ctbmv: fortran
ctbsv: fortran
ctpmv: fortran
ctpsv: fortran
ctrmm: fortran
ctrmv: fortran
ctrsm: fortran
ctrsv: fortran
dasum: fortran
daxpy: fortran
dcopy: fortran
ddot: fortran
dgbmv: fortran
dgemm: fortran
dgemv: fortran
dger: fortran
dnrm2: fortran
drot: fortran
drotg: fortran
drotm: fortran
drotmg: fortran
dsbmv: fortran
dscal: fortran
dspmv: fortran
dspr: fortran
dspr2: fortran
dswap: fortran
dsymm: fortran
dsymv: fortran
dsyr: fortran
dsyr2: fortran
dsyr2k: fortran
dsyrk: fortran
dtbmv: fortran
dtbsv: fortran
dtpmv: fortran
dtpsv: fortran
dtrmm: fortran
dtrmv: fortran
dtrsm: fortran
dtrsv: fortran
dzasum: fortran
dznrm2: fortran
icamax: fortran
idamax: fortran
isamax: fortran
izamax: fortran
sasum: fortran
saxpy: fortran
scasum: fortran
scnrm2: fortran
scopy: fortran
sdot: fortran
sgbmv: fortran
sgemm: fortran
sgemv: fortran
sger: fortran
snrm2: fortran
srot: fortran
srotg: fortran
srotm: fortran
srotmg: fortran
ssbmv: fortran
sscal: fortran
sspmv: fortran
sspr: fortran
sspr2: fortran
sswap: fortran
ssymm: fortran
ssymv: fortran
ssyr: fortran
ssyr2: fortran
ssyr2k: fortran
ssyrk: fortran
stbmv: fortran
stbsv: fortran
stpmv: fortran
stpsv: fortran
strmm: fortran
strmv: fortran
strsm: fortran
strsv: fortran
zaxpy: fortran
zcopy: fortran
zdotc: fortran
zdotu: fortran
zdrot: fortran
zdscal: fortran
zgbmv: fortran
zgemm: fortran
zgemv: fortran
zgerc: fortran
zgeru: fortran
zhbmv: fortran
zhemm: fortran
zhemv: fortran
zher: fortran
zher2: fortran
zher2k: fortran
zherk: fortran
zhpmv: fortran
zhpr: fortran
zhpr2: fortran
zrotg: fortran
zscal: fortran
zspmv: fortran
zspr: fortran
zswap: fortran
zsymm: fortran
zsyr: fortran
zsyr2k: fortran
zsyrk: fortran
ztbmv: fortran
ztbsv: fortran
ztpmv: fortran
ztpsv: fortran
ztrmm: fortran
ztrmv: fortran
ztrsm: fortran
ztrsv: fortran
