__f2py_numpy_version__: str
__version__: str
id_srand: fortran
id_srandi: fortran
id_srando: fortran
idd_copycols: fortran
idd_diffsnorm: fortran
idd_estrank: fortran
idd_findrank: fortran
idd_frm: fortran
idd_frmi: fortran
idd_id2svd: fortran
idd_reconid: fortran
idd_reconint: fortran
idd_sfrm: fortran
idd_sfrmi: fortran
idd_snorm: fortran
iddp_aid: fortran
iddp_asvd: fortran
iddp_id: fortran
iddp_rid: fortran
iddp_rsvd: fortran
iddp_svd: fortran
iddr_aid: fortran
iddr_aidi: fortran
iddr_asvd: fortran
iddr_id: fortran
iddr_rid: fortran
iddr_rsvd: fortran
iddr_svd: fortran
idz_copycols: fortran
idz_diffsnorm: fortran
idz_estrank: fortran
idz_findrank: fortran
idz_frm: fortran
idz_frmi: fortran
idz_id2svd: fortran
idz_reconid: fortran
idz_reconint: fortran
idz_sfrm: fortran
idz_sfrmi: fortran
idz_snorm: fortran
idzp_aid: fortran
idzp_asvd: fortran
idzp_id: fortran
idzp_rid: fortran
idzp_rsvd: fortran
idzp_svd: fortran
idzr_aid: fortran
idzr_aidi: fortran
idzr_asvd: fortran
idzr_id: fortran
idzr_rid: fortran
idzr_rsvd: fortran
idzr_svd: fortran
