def id_srand(n): ...
def id_srandi(t) -> None: ...
def id_srando() -> None: ...
def idd_frm(n, w, x): ...
def idd_sfrm(l, n, w, x): ...
def idd_frmi(m): ...
def idd_sfrmi(l, m): ...
def iddp_id(eps, A): ...
def iddr_id(A, k): ...
def idd_reconid(B, idx, proj): ...
def idd_reconint(idx, proj): ...
def idd_copycols(A, k, idx): ...
def idd_id2svd(B, idx, proj): ...
def idd_snorm(m, n, matvect, matvec, its: int = ...): ...
def idd_diffsnorm(m, n, matvect, matvect2, matvec, matvec2, its: int = ...): ...
def iddr_svd(A, k): ...
def iddp_svd(eps, A): ...
def iddp_aid(eps, A): ...
def idd_estrank(eps, A): ...
def iddp_asvd(eps, A): ...
def iddp_rid(eps, m, n, matvect): ...
def idd_findrank(eps, m, n, matvect): ...
def iddp_rsvd(eps, m, n, matvect, matvec): ...
def iddr_aid(A, k): ...
def iddr_aidi(m, n, k): ...
def iddr_asvd(A, k): ...
def iddr_rid(m, n, matvect, k): ...
def iddr_rsvd(m, n, matvect, matvec, k): ...
def idz_frm(n, w, x): ...
def idz_sfrm(l, n, w, x): ...
def idz_frmi(m): ...
def idz_sfrmi(l, m): ...
def idzp_id(eps, A): ...
def idzr_id(A, k): ...
def idz_reconid(B, idx, proj): ...
def idz_reconint(idx, proj): ...
def idz_copycols(A, k, idx): ...
def idz_id2svd(B, idx, proj): ...
def idz_snorm(m, n, matveca, matvec, its: int = ...): ...
def idz_diffsnorm(m, n, matveca, matveca2, matvec, matvec2, its: int = ...): ...
def idzr_svd(A, k): ...
def idzp_svd(eps, A): ...
def idzp_aid(eps, A): ...
def idz_estrank(eps, A): ...
def idzp_asvd(eps, A): ...
def idzp_rid(eps, m, n, matveca): ...
def idz_findrank(eps, m, n, matveca): ...
def idzp_rsvd(eps, m, n, matveca, matvec): ...
def idzr_aid(A, k): ...
def idzr_aidi(m, n, k): ...
def idzr_asvd(A, k): ...
def idzr_rid(m, n, matveca, k): ...
def idzr_rsvd(m, n, matveca, matvec, k): ...
