from ._expm_frechet import expm_cond as expm_cond, expm_frechet as expm_frechet
from ._matfuncs_sqrtm import sqrtm as sqrtm

def fractional_matrix_power(A, t): ...
def logm(A, disp: bool = ...): ...
def expm(A): ...
def cosm(A): ...
def sinm(A): ...
def tanm(A): ...
def coshm(A): ...
def sinhm(A): ...
def tanhm(A): ...
def funm(A, func, disp: bool = ...): ...
def signm(A, disp: bool = ...): ...
def khatri_rao(a, b): ...
