from _typeshed import Incomplete

def solve_sylvester(a, b, q): ...
def solve_continuous_lyapunov(a, q): ...
solve_lyapunov = solve_continuous_lyapunov

def solve_discrete_lyapunov(a, q, method: Incomplete | None = ...): ...
def solve_continuous_are(a, b, q, r, e: Incomplete | None = ..., s: Incomplete | None = ..., balanced: bool = ...): ...
def solve_discrete_are(a, b, q, r, e: Incomplete | None = ..., s: Incomplete | None = ..., balanced: bool = ...): ...
