from _typeshed import Incomplete

class _FakeMatrix:
    __array_interface__: Incomplete
    def __init__(self, data) -> None: ...

class _FakeMatrix2:
    def __init__(self, data) -> None: ...
    def __array__(self): ...

def assert_no_overwrite(call, shapes, dtypes: Incomplete | None = ...) -> None: ...
