from scipy.linalg._fblas import *
from _typeshed import Incomplete

def find_best_blas_type(arrays=..., dtype: Incomplete | None = ...): ...
def get_blas_funcs(names, arrays=..., dtype: Incomplete | None = ..., ilp64: bool = ...): ...
