from _typeshed import Incomplete

def c2c(forward, x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...

fft: Incomplete
ifft: Incomplete

def r2c(forward, x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...

rfft: Incomplete
ihfft: Incomplete

def c2r(forward, x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...

hfft: Incomplete
irfft: Incomplete

def fft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def ifft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def rfft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def irfft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def hfft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def ihfft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def c2cn(forward, x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...

fftn: Incomplete
ifftn: Incomplete

def r2cn(forward, x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...

rfftn: Incomplete
ihfftn: Incomplete

def c2rn(forward, x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...

hfftn: Incomplete
irfftn: Incomplete

def r2r_fftpack(forward, x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...

rfft_fftpack: Incomplete
irfft_fftpack: Incomplete
