import numpy as np

def entropy(pk: np.typing.ArrayLike, qk: np.typing.ArrayLike | None = ..., base: float | None = ..., axis: int = ...) -> np.number | np.ndarray: ...
def differential_entropy(values: np.typing.ArrayLike, *, window_length: int | None = ..., base: float | None = ..., axis: int = ..., method: str = ...) -> np.number | np.ndarray: ...
