from _typeshed import Incomplete

def hdquantiles(data, prob=..., axis: Incomplete | None = ..., var: bool = ...): ...
def hdmedian(data, axis: int = ..., var: bool = ...): ...
def hdquantiles_sd(data, prob=..., axis: Incomplete | None = ...): ...
def trimmed_mean_ci(data, limits=..., inclusive=..., alpha: float = ..., axis: Incomplete | None = ...): ...
def mjci(data, prob=..., axis: Incomplete | None = ...): ...
def mquantiles_cimj(data, prob=..., alpha: float = ..., axis: Incomplete | None = ...): ...
def median_cihs(data, alpha: float = ..., axis: Incomplete | None = ...): ...
def compare_medians_ms(group_1, group_2, axis: Incomplete | None = ...): ...
def idealfourths(data, axis: Incomplete | None = ...): ...
def rsh(data, points: Incomplete | None = ...): ...
