from _typeshed import Incomplete

def linregress(x, y: Incomplete | None = ..., alternative: str = ...): ...
def theilslopes(y, x: Incomplete | None = ..., alpha: float = ..., method: str = ...): ...
def siegelslopes(y, x: Incomplete | None = ..., method: str = ...): ...

# Names in __all__ with no definition:
#   _find_repeats
