import scipy as scipy
from scipy.linalg._basic import solve_triangular as solve_triangular

__pyx_capi__: dict
__test__: dict
gaussian_kernel_estimate: fused_cython_function
gaussian_kernel_estimate_log: fused_cython_function

def genhyperbolic_logpdf(*args, **kwargs): ...
def genhyperbolic_pdf(*args, **kwargs): ...
def geninvgauss_logpdf(*args, **kwargs): ...
def von_mises_cdf(*args, **kwargs): ...
