from _typeshed import Incomplete

def fft(x, n: Incomplete | None = ..., axis: int = ..., overwrite_x: bool = ...): ...
def ifft(x, n: Incomplete | None = ..., axis: int = ..., overwrite_x: bool = ...): ...
def rfft(x, n: Incomplete | None = ..., axis: int = ..., overwrite_x: bool = ...): ...
def irfft(x, n: Incomplete | None = ..., axis: int = ..., overwrite_x: bool = ...): ...
def fftn(x, shape: Incomplete | None = ..., axes: Incomplete | None = ..., overwrite_x: bool = ...): ...
def ifftn(x, shape: Incomplete | None = ..., axes: Incomplete | None = ..., overwrite_x: bool = ...): ...
def fft2(x, shape: Incomplete | None = ..., axes=..., overwrite_x: bool = ...): ...
def ifft2(x, shape: Incomplete | None = ..., axes=..., overwrite_x: bool = ...): ...
