from _typeshed import Incomplete

def diff(x, order: int = ..., period: Incomplete | None = ..., _cache=...): ...
def tilbert(x, h, period: Incomplete | None = ..., _cache=...): ...
def itilbert(x, h, period: Incomplete | None = ..., _cache=...): ...
def hilbert(x, _cache=...): ...
def ihilbert(x): ...
def cs_diff(x, a, b, period: Incomplete | None = ..., _cache=...): ...
def sc_diff(x, a, b, period: Incomplete | None = ..., _cache=...): ...
def ss_diff(x, a, b, period: Incomplete | None = ..., _cache=...): ...
def cc_diff(x, a, b, period: Incomplete | None = ..., _cache=...): ...
def shift(x, a, period: Incomplete | None = ..., _cache=...): ...
