from _typeshed import Incomplete

def dctn(x, type: int = ..., shape: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...
def idctn(x, type: int = ..., shape: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...
def dstn(x, type: int = ..., shape: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...
def idstn(x, type: int = ..., shape: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...
def dct(x, type: int = ..., n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...
def idct(x, type: int = ..., n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...
def dst(x, type: int = ..., n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...
def idst(x, type: int = ..., n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ...): ...
