from scipy.fft._pocketfft.pypocketfft import r2r_fftpack as r2r_fftpack

__test__: dict

def convolve(*args, **kwargs): ...
def convolve_z(*args, **kwargs): ...
def destroy_convolve_cache(*args, **kwargs): ...
def init_convolution_kernel(*args, **kwargs): ...
