from ._fitpack_impl import bisplev as bisplev, bisplrep as bisplrep
from _typeshed import Incomplete

def splprep(x, w: Incomplete | None = ..., u: Incomplete | None = ..., ub: Incomplete | None = ..., ue: Incomplete | None = ..., k: int = ..., task: int = ..., s: Incomplete | None = ..., t: Incomplete | None = ..., full_output: int = ..., nest: Incomplete | None = ..., per: int = ..., quiet: int = ...): ...
def splrep(x, y, w: Incomplete | None = ..., xb: Incomplete | None = ..., xe: Incomplete | None = ..., k: int = ..., task: int = ..., s: Incomplete | None = ..., t: Incomplete | None = ..., full_output: int = ..., per: int = ..., quiet: int = ...): ...
def splev(x, tck, der: int = ..., ext: int = ...): ...
def splint(a, b, tck, full_output: int = ...): ...
def sproot(tck, mest: int = ...): ...
def spalde(x, tck): ...
def insert(x, tck, m: int = ..., per: int = ...): ...
def splder(tck, n: int = ...): ...
def splantider(tck, n: int = ...): ...
