__f2py_numpy_version__: str
__version__: str
bispeu: fortran
bispev: fortran
curfit: fortran
dblint: fortran
fpchec: fortran
fpcurf0: fortran
fpcurf1: fortran
fpcurfm1: fortran
parcur: fortran
parder: fortran
pardeu: fortran
pardtc: fortran
percur: fortran
regrid_smth: fortran
regrid_smth_spher: fortran
spalde: fortran
spherfit_lsq: fortran
spherfit_smth: fortran
splder: fortran
splev: fortran
splint: fortran
sproot: fortran
surfit_lsq: fortran
surfit_smth: fortran
types: fortran
