[knn_params]
k_values = [1, 2, 3, 5, 7]
distance_metric = "euclidean"

[dataset]
format = "csv"
training_set = "adult.csv"
test_set = "adult.t.csv"
category_indexes = [1, 3, 5, 6, 7, 8, 9, 13]
perturb_categories = [9]

[abstraction]
epsilon = 0.01

