from scipy.special._precompute.utils import lagrange_inversion as lagrange_inversion

def compute_a(n): ...
def compute_g(n): ...
def eta(lam): ...
def compute_alpha(n): ...
def compute_d(K, N): ...

header: str
footer: str

def main() -> None: ...
