from scipy.special._mptestutils import mpf2float as mpf2float

exp_inf: float

def rgamma_cached(x, dps): ...
def mp_wright_bessel(a, b, x, dps: int = ..., maxterms: int = ...): ...
def main() -> None: ...
