from scipy.integrate import quad as quad
from scipy.optimize import curve_fit as curve_fit, minimize_scalar as minimize_scalar

def series_small_a(): ...
def dg_series(z, n): ...
def pg_series(k, z, n): ...
def series_small_a_small_b(): ...
def asymptotic_series(): ...
def optimal_epsilon_integral(): ...
def main(): ...
