from _typeshed import Incomplete

def equality_constrained_sqp(fun_and_constr, grad_and_jac, lagr_hess, x0, fun0, grad0, constr0, jac0, stop_criteria, state, initial_penalty, initial_trust_radius, factorization_method, trust_lb: Incomplete | None = ..., trust_ub: Incomplete | None = ..., scaling=...): ...
