from _typeshed import Incomplete

def eqp_kktfact(H, c, A, b): ...
def sphere_intersections(z, d, trust_radius, entire_line: bool = ...): ...
def box_intersections(z, d, lb, ub, entire_line: bool = ...): ...
def box_sphere_intersections(z, d, lb, ub, trust_radius, entire_line: bool = ..., extra_info: bool = ...): ...
def inside_box_boundaries(x, lb, ub): ...
def modified_dogleg(A, Y, b, trust_radius, lb, ub): ...
def projected_cg(H, c, Z, Y, b, trust_radius=..., lb: Incomplete | None = ..., ub: Incomplete | None = ..., tol: Incomplete | None = ..., max_iter: Incomplete | None = ..., max_infeasible_iter: Incomplete | None = ..., return_all: bool = ...): ...
