from typing import Any

__pyx_capi__: dict
__test__: dict
idx: int
sig: tuple
sigs: list

def check_capsule(item) -> Any: ...
def get_capsule_signature(*args, **kwargs): ...
def get_raw_capsule(ptr, name, context) -> Any: ...
def test_call_cython(*args, **kwargs): ...
