from _typeshed import Incomplete
from collections.abc import Generator

class ReferenceError(AssertionError): ...

def set_gc_state(state) -> None: ...
def gc_state(state) -> Generator[None, None, None]: ...
def assert_deallocated(func, *args, **kwargs) -> Generator[Incomplete, None, None]: ...
