def test_call_nodata(*args, **kwargs): ...
def test_call_nonlocal(*args, **kwargs): ...
def test_call_simple(*args, **kwargs): ...
def test_get_data_capsule(*args, **kwargs): ...
def test_get_plus1_capsule(*args, **kwargs): ...
def test_get_plus1b_capsule(*args, **kwargs): ...
def test_get_plus1bc_capsule(*args, **kwargs): ...
