from _typeshed import Incomplete
from collections.abc import Generator

def tempdir() -> Generator[Incomplete, None, None]: ...
def in_tempdir() -> Generator[Incomplete, None, None]: ...
def in_dir(dir: Incomplete | None = ...) -> Generator[Incomplete, None, None]: ...
