class _DeprecationHelperStr:
    def __init__(self, content, message) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...

# Names in __all__ with no definition:
#   _deprecated
