from _typeshed import Incomplete

def docformat(docstring, docdict: Incomplete | None = ...): ...
def inherit_docstring_from(cls): ...
def extend_notes_in_docstring(cls, notes): ...
def replace_notes_in_docstring(cls, notes): ...
def indentcount_lines(lines): ...
def filldoc(docdict, unindent_params: bool = ...): ...
def unindent_dict(docdict): ...
def unindent_string(docstring): ...
def doc_replace(obj, oldval, newval): ...
