from _typeshed import Incomplete
from scipy._lib.uarray import Dispatchable as Dispatchable, generate_multimethod as generate_multimethod

def fft(x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def ifft(x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def rfft(x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def irfft(x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def hfft(x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def ihfft(x, n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def fftn(x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def ifftn(x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def fft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def ifft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def rfftn(x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def rfft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def irfftn(x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def irfft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def hfftn(x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def hfft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def ihfftn(x, s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
def ihfft2(x, s: Incomplete | None = ..., axes=..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, plan: Incomplete | None = ...): ...
