def fht(a, dln, mu, offset: float = ..., bias: float = ...): ...
def ifht(A, dln, mu, offset: float = ..., bias: float = ...): ...
def fhtoffset(dln, mu, initial: float = ..., bias: float = ...): ...
