from _typeshed import Incomplete

def dctn(x, type: int = ..., s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., *, orthogonalize: Incomplete | None = ...): ...
def idctn(x, type: int = ..., s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., orthogonalize: Incomplete | None = ...): ...
def dstn(x, type: int = ..., s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., orthogonalize: Incomplete | None = ...): ...
def idstn(x, type: int = ..., s: Incomplete | None = ..., axes: Incomplete | None = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., orthogonalize: Incomplete | None = ...): ...
def dct(x, type: int = ..., n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., orthogonalize: Incomplete | None = ...): ...
def idct(x, type: int = ..., n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., orthogonalize: Incomplete | None = ...): ...
def dst(x, type: int = ..., n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., orthogonalize: Incomplete | None = ...): ...
def idst(x, type: int = ..., n: Incomplete | None = ..., axis: int = ..., norm: Incomplete | None = ..., overwrite_x: bool = ..., workers: Incomplete | None = ..., orthogonalize: Incomplete | None = ...): ...
