__f2py_numpy_version__: str
__version__: str
cbicgrevcom: fortran
cbicgstabrevcom: fortran
ccgrevcom: fortran
ccgsrevcom: fortran
cgmresrevcom: fortran
cqmrrevcom: fortran
dbicgrevcom: fortran
dbicgstabrevcom: fortran
dcgrevcom: fortran
dcgsrevcom: fortran
dgmresrevcom: fortran
dqmrrevcom: fortran
sbicgrevcom: fortran
sbicgstabrevcom: fortran
scgrevcom: fortran
scgsrevcom: fortran
sgmresrevcom: fortran
sqmrrevcom: fortran
zbicgrevcom: fortran
zbicgstabrevcom: fortran
zcgrevcom: fortran
zcgsrevcom: fortran
zgmresrevcom: fortran
zqmrrevcom: fortran
