class FortranEOFError(TypeError, OSError): ...
class FortranFormattingError(TypeError, OSError): ...

class FortranFile:
    def __init__(self, filename, mode: str = ..., header_dtype=...) -> None: ...
    def write_record(self, *items) -> None: ...
    def read_record(self, *dtypes, **kwargs): ...
    def read_ints(self, dtype: str = ...): ...
    def read_reals(self, dtype: str = ...): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None) -> None: ...
