# Names in __all__ with no definition:
#   ABSENT
#   FILLMAP
#   FILL_BYTE
#   FILL_CHAR
#   FILL_DOUBLE
#   FILL_FLOAT
#   FILL_INT
#   FILL_SHORT
#   IS_PYPY
#   LITTLE_ENDIAN
#   NC_ATTRIBUTE
#   NC_BYTE
#   NC_CHAR
#   NC_DIMENSION
#   NC_DOUBLE
#   NC_FLOAT
#   NC_INT
#   NC_SHORT
#   NC_VARIABLE
#   NetCDFFile
#   NetCDFVariable
#   REVERSE
#   TYPEMAP
#   ZERO
#   array
#   netcdf_file
#   netcdf_variable
