def central_diff_weights(Np, ndiv: int = ...): ...
def derivative(func, x0, dx: float = ..., n: int = ..., args=..., order: int = ...): ...
def ascent(): ...
def face(gray: bool = ...): ...
def electrocardiogram(): ...
