from _typeshed import Incomplete

def mat_reader_factory(file_name, appendmat: bool = ..., **kwargs): ...
def loadmat(file_name, mdict: Incomplete | None = ..., appendmat: bool = ..., **kwargs): ...
def savemat(file_name, mdict, appendmat: bool = ..., format: str = ..., long_field_names: bool = ..., do_compression: bool = ..., oned_as: str = ...) -> None: ...
def whosmat(file_name, appendmat: bool = ..., **kwargs): ...
