from typing import ClassVar

BLOCK_SIZE: int
__pyx_capi__: dict
__test__: dict

class GenericStream:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def all_data_read(self, *args, **kwargs): ...
    def read(self, *args, **kwargs): ...
    def seek(self, *args, **kwargs): ...
    def tell(self, *args, **kwargs): ...
    def __reduce__(self): ...

class ZlibInputStream(GenericStream):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def all_data_read(self, *args, **kwargs): ...
    def read(self, *args, **kwargs): ...
    def seek(self, *args, **kwargs): ...
    def tell(self, *args, **kwargs): ...
    def __reduce__(self): ...

def make_stream(*args, **kwargs): ...
