# Names in __all__ with no definition:
#   MatFile4Reader
#   MatFile4Writer
#   MatFileReader
#   SYS_LITTLE_ENDIAN
#   VarHeader4
#   VarReader4
#   VarWriter4
#   arr_dtype_number
#   arr_to_2d
#   arr_to_chars
#   chars_to_strings
#   convert_dtypes
#   docfiller
#   matdims
#   mclass_info
#   mdtypes_template
#   miDOUBLE
#   miINT16
#   miINT32
#   miSINGLE
#   miUINT16
#   miUINT8
#   mxCHAR_CLASS
#   mxFULL_CLASS
#   mxSPARSE_CLASS
#   np_to_mtypes
#   order_codes
#   read_dtype
#   squeeze_element
