# Names in __all__ with no definition:
#   BytesIO
#   EmptyStructMarker
#   MDTYPES
#   MatFile5Reader
#   MatFile5Writer
#   MatFileReader
#   MatReadError
#   MatReadWarning
#   MatWriteError
#   MatlabFunction
#   MatlabObject
#   NDT_ARRAY_FLAGS
#   NDT_FILE_HDR
#   NDT_TAG_FULL
#   NDT_TAG_SMALL
#   NP_TO_MTYPES
#   NP_TO_MXTYPES
#   VarReader5
#   VarWriter5
#   ZlibInputStream
#   arr_dtype_number
#   arr_to_chars
#   docfiller
#   mat_struct
#   matdims
#   mclass_info
#   miCOMPRESSED
#   miINT8
#   miMATRIX
#   miUINT32
#   miUTF8
#   mxCELL_CLASS
#   mxCHAR_CLASS
#   mxDOUBLE_CLASS
#   mxOBJECT_CLASS
#   mxSPARSE_CLASS
#   mxSTRUCT_CLASS
#   native_code
#   read_dtype
#   swapped_code
#   to_writeable
#   varmats_from_mat
